using System.Text;
using PermissionScanner.Core.Models;

namespace PermissionScanner.Core.Services;

/// <summary>
/// Generates FluentMigrator migration files for seeding permissions.
/// </summary>
public class MigrationFileGenerator
{
    /// <summary>
    /// Generates a migration file for seeding permissions grouped by resource.
    /// </summary>
    public static string GenerateMigrationFile(
        string resourceName,
        List<PermissionDefinition> permissions,
        long migrationTimestamp,
        int displayOrderStart = 1)
    {
        var sb = new StringBuilder();
        
        // Class name: Seed{Resource}Permissions (e.g., SeedProductPermissions)
        var className = GenerateClassName(resourceName);
        var migrationNumber = migrationTimestamp;
        
        // File header
        sb.AppendLine("using FluentMigrator;");
        sb.AppendLine();
        sb.AppendLine("namespace KS.MigrationService.Migrations.Stage2_IdentityAccess;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Seeds {resourceName} permissions for fine-grained access control");
        sb.AppendLine($"/// Auto-generated by Permission Scanner Tool - DO NOT EDIT MANUALLY");
        sb.AppendLine($"/// Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[Migration({migrationNumber})]");
        sb.AppendLine($"public class {className} : BaseMigration");
        sb.AppendLine("{");
        sb.AppendLine("    public override void PerformUpgrade()");
        sb.AppendLine("    {");
        sb.AppendLine("        var schemaName = GetAppSchemaName();");
        sb.AppendLine("        ");
        sb.AppendLine("        // Insert permissions");
        sb.AppendLine("        Execute.Sql($@\"");
        sb.AppendLine("            INSERT INTO {schemaName}.permissions (");
        sb.AppendLine("                permission_name, ");
        sb.AppendLine("                permission_description, ");
        sb.AppendLine("                resource, ");
        sb.AppendLine("                action, ");
        sb.AppendLine("                is_system_permission, ");
        sb.AppendLine("                is_active, ");
        sb.AppendLine("                display_order,");
        sb.AppendLine("                created_at,");
        sb.AppendLine("                updated_at,");
        sb.AppendLine("                version");
        sb.AppendLine("            ) VALUES ");
        
        // Generate VALUES clause
        var displayOrder = displayOrderStart;
        for (int i = 0; i < permissions.Count; i++)
        {
            var permission = permissions[i];
            var isLast = i == permissions.Count - 1;
            
            sb.AppendLine("            -- " + CapitalizeFirst(permission.Action) + " " + permission.Resource.Replace(":", " "));
            sb.AppendLine("            (");
            sb.AppendLine($"                '{permission.PermissionName}',");
            sb.AppendLine($"                '{EscapeSqlString(permission.Description)}',");
            sb.AppendLine($"                '{permission.Resource}',");
            sb.AppendLine($"                '{permission.Action}',");
            sb.AppendLine("                true,");
            sb.AppendLine("                true,");
            sb.AppendLine($"                {displayOrder},");
            sb.AppendLine("                NOW(),");
            sb.AppendLine("                NOW(),");
            sb.AppendLine("                1");
            sb.Append("            )");
            
            if (!isLast)
                sb.AppendLine(",");
            else
                sb.AppendLine();
            
            displayOrder++;
        }
        
        sb.AppendLine("            ON CONFLICT (permission_name) DO NOTHING;");
        sb.AppendLine("        \");");
        sb.AppendLine();
        sb.AppendLine($"        Console.WriteLine(\"✅ Seeded {resourceName} permissions:\");");
        foreach (var permission in permissions)
        {
            sb.AppendLine($"        Console.WriteLine(\"   - {permission.PermissionName} - {permission.Description}\");");
        }
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    public override void PerformDowngrade()");
        sb.AppendLine("    {");
        sb.AppendLine("        var schemaName = GetAppSchemaName();");
        sb.AppendLine("        ");
        sb.AppendLine("        // Remove permissions");
        sb.AppendLine("        Execute.Sql($@\"");
        sb.AppendLine("            DELETE FROM {schemaName}.permissions ");
        sb.AppendLine("            WHERE permission_name IN (");
        
        // Generate permission name list for DELETE
        for (int i = 0; i < permissions.Count; i++)
        {
            var permission = permissions[i];
            var isLast = i == permissions.Count - 1;
            sb.Append($"                '{permission.PermissionName}'");
            if (!isLast)
                sb.AppendLine(",");
            else
                sb.AppendLine();
        }
        
        sb.AppendLine("            )");
        sb.AppendLine("              AND is_system_permission = true;");
        sb.AppendLine("        \");");
        sb.AppendLine("        ");
        sb.AppendLine($"        Console.WriteLine(\"✅ Removed {resourceName} permissions\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    /// <summary>
    /// Generates a class name from resource name (e.g., "products" → "SeedProductPermissions").
    /// </summary>
    private static string GenerateClassName(string resourceName)
    {
        // Convert "products:variants" → "ProductsVariants"
        var parts = resourceName.Split(':', '-');
        var className = string.Join("", parts.Select(CapitalizeFirst));
        return $"Seed{className}Permissions";
    }

    /// <summary>
    /// Escapes SQL string to prevent SQL injection and syntax errors.
    /// </summary>
    private static string EscapeSqlString(string text)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;
        
        return text
            .Replace("'", "''")  // Escape single quotes
            .Replace("\r", " ")
            .Replace("\n", " ");
    }

    /// <summary>
    /// Capitalizes the first letter of a string.
    /// </summary>
    private static string CapitalizeFirst(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;
        
        // Handle camelCase conversion
        if (text.Length == 1)
            return text.ToUpper();
        
        return char.ToUpper(text[0]) + text.Substring(1);
    }

    /// <summary>
    /// Generates a migration timestamp (YYYYMMDDHHMMSS format).
    /// </summary>
    public static long GenerateMigrationTimestamp(int offsetSeconds = 0)
    {
        var now = DateTime.UtcNow.AddSeconds(offsetSeconds);
        return long.Parse(now.ToString("yyyyMMddHHmmss"));
    }

    /// <summary>
    /// Finds the next available migration timestamp by checking existing migrations.
    /// </summary>
    public static long GetNextMigrationTimestamp(string migrationServicePath)
    {
        var migrationsDir = Path.Combine(migrationServicePath, "Migrations", "Stage2_IdentityAccess");
        if (!Directory.Exists(migrationsDir))
            return GenerateMigrationTimestamp();
        
        var migrationFiles = Directory.GetFiles(migrationsDir, "*.cs", SearchOption.TopDirectoryOnly);
        var maxTimestamp = 0L;
        
        foreach (var file in migrationFiles)
        {
            var fileName = Path.GetFileNameWithoutExtension(file);
            var match = System.Text.RegularExpressions.Regex.Match(fileName, @"^(\d{14})");
            if (match.Success && long.TryParse(match.Groups[1].Value, out var timestamp))
            {
                if (timestamp > maxTimestamp)
                    maxTimestamp = timestamp;
            }
        }
        
        // If no migrations found, use current timestamp
        if (maxTimestamp == 0)
            return GenerateMigrationTimestamp();
        
        // Return next timestamp (add 1 second to ensure uniqueness)
        return maxTimestamp + 1;
    }

    /// <summary>
    /// Calculates the starting display_order for new permissions by finding the max in existing migrations.
    /// </summary>
    public static int CalculateDisplayOrderStart(string migrationServicePath)
    {
        var migrationsDir = Path.Combine(migrationServicePath, "Migrations", "Stage2_IdentityAccess");
        if (!Directory.Exists(migrationsDir))
            return 1;
        
        var migrationFiles = Directory.GetFiles(migrationsDir, "*.cs", SearchOption.TopDirectoryOnly)
            .Where(f => f.Contains("Seed") && f.Contains("Permission"))
            .ToList();
        
        var maxDisplayOrder = 0;
        
        foreach (var file in migrationFiles)
        {
            var content = File.ReadAllText(file);
            var matches = System.Text.RegularExpressions.Regex.Matches(content, @"display_order,\s*(\d+)");
            foreach (System.Text.RegularExpressions.Match match in matches)
            {
                if (int.TryParse(match.Groups[1].Value, out var order) && order > maxDisplayOrder)
                {
                    maxDisplayOrder = order;
                }
            }
        }
        
        return maxDisplayOrder + 1;
    }
}
