using System.Text;
using PermissionScanner.Core.Models;

namespace PermissionScanner.Core.Generators;

/// <summary>
/// Generates TypeScript constants from backend permissions for use in the frontend.
/// Enables single source of truth: frontend imports BACKEND_PERMISSIONS from generated file.
/// </summary>
public static class FrontendPermissionConstantsGenerator
{
    /// <summary>
    /// Generates TypeScript file content: BACKEND_PERMISSIONS = { ConstantName: "permission:value", ... }.
    /// Deduplicates by ConstantName (first occurrence wins).
    /// </summary>
    public static string GenerateTypeScript(IEnumerable<PermissionDefinition> permissions)
    {
        var seen = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in permissions)
        {
            if (string.IsNullOrWhiteSpace(p.ConstantName) || string.IsNullOrWhiteSpace(p.PermissionName))
                continue;
            if (!seen.ContainsKey(p.ConstantName))
                seen[p.ConstantName] = p.PermissionName;
        }

        var sb = new StringBuilder();
        sb.AppendLine("/**");
        sb.AppendLine(" * Backend permission constants. Auto-generated by Permission Scanner.");
        sb.AppendLine(" * Do not edit manually. Regenerate: dotnet run --project PermissionScanner.Cli generate --solution ../../kronos-services --platform-services ../../kronos-services/Kronos.Sales.PlatformServices --update-files --emit-frontend ../../kronos-app");
        sb.AppendLine(" * Source: backend Permissions.cs (PlatformServices + services).");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine("export const BACKEND_PERMISSIONS = {");

        foreach (var kv in seen.OrderBy(k => k.Key))
        {
            var value = kv.Value.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"  {kv.Key}: \"{value}\",");
        }

        sb.AppendLine("} as const;");
        sb.AppendLine();
        sb.AppendLine("export type BackendPermission = (typeof BACKEND_PERMISSIONS)[keyof typeof BACKEND_PERMISSIONS];");
        return sb.ToString();
    }
}
